# fly.toml app configuration file generated for hello-fly-private-3eriiq on 2026-07-31T15:14:59Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'hello-fly-private-3eriiq'
primary_region = 'gru'
kill_signal = 'SIGINT'
kill_timeout = '6s'
swap_size_mb = 0

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'suspend'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
  processes = ['app']
  size = 'shared-cpu-1x'

[deploy]
  release_command = 'sleep 10'
  release_command_timeout = '1m'
  strategy = 'bluegreen'

[[restart]]
  policy = 'never'
  processes = ['app']
  retries = 10
