# fly.toml app configuration file generated for hello-fly-private-h713zq on 2026-08-20T12:56:11Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'hello-fly-private-h713zq'
primary_region = 'ams'
kill_signal = 'SIGINT'
kill_timeout = '6s'
swap_size_mb = 0

[build]

[deploy]
  strategy = 'canary'
  max_unavailable = 0.99
  release_command = 'sleep 10'
  release_command_timeout = '1m0s'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'suspend'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[restart]]
  policy = 'never'
  retries = 10
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256

[[vm]]
  size = 'shared-cpu-1x'
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
  processes = ['app']
